(function exposeTemplates(root, factory) {
  const templates = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = templates;
  else root.invitationTemplates = templates;
})(typeof globalThis !== "undefined" ? globalThis : this, function buildTemplates() {
  return [
    { id: "ivory-garden", name: "Ivory Garden", category: "Wedding", price: 49, tier: "Essential", description: "Airy florals, classic serif type, and a graceful centered ceremony card.", accent: "#8a6846", canvas: "#f1ece4", paper: "#fffdf8", layout: "classic", image: "/assets/templates/ivory-garden.webp" },
    { id: "olive-press", name: "Olive Press", category: "Wedding", price: 49, tier: "Essential", description: "Mediterranean green, fine rules, and understated editorial typography.", accent: "#586747", canvas: "#dfe4d8", paper: "#fbfcf7", layout: "bordered", image: "/assets/templates/olive-press.webp" },
    { id: "blush-letter", name: "Blush Letter", category: "Engagement", price: 49, tier: "Essential", description: "A romantic letter-style invitation with blush paper and delicate details.", accent: "#a65f67", canvas: "#ead7d8", paper: "#fff8f7", layout: "letter", image: "/assets/templates/blush-letter.webp" },
    { id: "baptism-light", name: "Baptism Light", category: "Baptism", price: 49, tier: "Essential", description: "Luminous white and powder blue with a calm, ceremonial composition.", accent: "#64849c", canvas: "#dce8ee", paper: "#ffffff", layout: "halo", image: "/assets/templates/baptism-light.webp" },
    { id: "confetti-pop", name: "Confetti Pop", category: "Birthday", price: 49, tier: "Essential", description: "Bright, playful color blocks for joyful birthdays and family celebrations.", accent: "#e34665", canvas: "#ffd84d", paper: "#fffdf4", layout: "playful", image: "/assets/templates/confetti-pop.webp" },
    { id: "corporate-line", name: "Corporate Line", category: "Business", price: 49, tier: "Essential", description: "A crisp schedule-first design for launches, openings, and company events.", accent: "#236b68", canvas: "#dce8e5", paper: "#ffffff", layout: "agenda", image: "/assets/templates/corporate-line.webp" },

    { id: "midnight-oud", name: "Midnight Oud", category: "Wedding", price: 69, tier: "Signature", description: "Charcoal, warm gold, and a formal evening mood with cinematic presence.", accent: "#d2a85e", canvas: "#111619", paper: "#191f22", layout: "cinematic", image: "/assets/templates/midnight-oud.webp" },
    { id: "terracotta-vows", name: "Terracotta Vows", category: "Wedding", price: 69, tier: "Signature", description: "Warm clay tones and architectural arches for modern destination weddings.", accent: "#a54f36", canvas: "#d8a28a", paper: "#fff8f0", layout: "arch", image: "/assets/templates/terracotta-vows.webp" },
    { id: "coastal-blue", name: "Coastal Blue", category: "Wedding", price: 69, tier: "Signature", description: "Sea-glass blue, open spacing, and a relaxed Mediterranean rhythm.", accent: "#39778a", canvas: "#c8dfe3", paper: "#f8ffff", layout: "coastal", image: "/assets/templates/coastal-blue.webp" },
    { id: "little-star", name: "Little Star", category: "Baptism", price: 69, tier: "Signature", description: "A gentle celestial layout for baptisms, newborn welcomes, and first birthdays.", accent: "#b58b3b", canvas: "#dce5f2", paper: "#fffdf8", layout: "celestial", image: "/assets/templates/little-star.webp" },
    { id: "modern-monogram", name: "Modern Monogram", category: "Other Celebrations", price: 69, tier: "Signature", description: "Large initials, clean geometry, and a confident contemporary grid.", accent: "#c3483f", canvas: "#e8e2dc", paper: "#fffdf9", layout: "monogram", image: "/assets/templates/modern-monogram.webp" },
    { id: "cedar-evening", name: "Cedar Evening", category: "Engagement", price: 69, tier: "Signature", description: "Deep cedar green and candle gold for an intimate Lebanese evening.", accent: "#d5ad62", canvas: "#173a32", paper: "#f7f2e7", layout: "split", image: "/assets/templates/cedar-evening.webp" },
    { id: "disco-bloom", name: "Disco Bloom", category: "Birthday", price: 69, tier: "Signature", description: "Bold floral energy and graphic type for a polished party invitation.", accent: "#6d45a3", canvas: "#f08ca8", paper: "#fff7df", layout: "poster", image: "/assets/templates/disco-bloom.webp" },

    { id: "eucharist-light", name: "Eucharist Light", category: "First Communion", price: 49, tier: "Essential", description: "Radiant ivory, white roses, wheat, and restrained gold for a timeless First Communion.", accent: "#a37a32", canvas: "#e9dfcc", paper: "#fffdf7", layout: "classic", image: "/assets/templates/eucharist-light.webp" },
    { id: "pearl-chapel", name: "Pearl Chapel", category: "First Communion", price: 69, tier: "Signature", description: "Pearl white, pale blue florals, and chapel architecture with a graceful ceremonial frame.", accent: "#6f879b", canvas: "#e1e9ed", paper: "#ffffff", layout: "cathedral", image: "/assets/templates/pearl-chapel.webp" },
    { id: "olive-blessing", name: "Olive Blessing", category: "First Communion", price: 89, tier: "Premium", description: "Mediterranean olive branches, warm halo light, and refined gold sacramental details.", accent: "#857035", canvas: "#ded8c7", paper: "#fffdf6", layout: "majlis", image: "/assets/templates/olive-blessing.webp" },

    { id: "sage-majlis", name: "Sage Majlis", category: "Wedding", price: 89, tier: "Premium", description: "A bilingual-ready, hospitality-led layout with soft botanical framing.", accent: "#2f7b68", canvas: "#cfded5", paper: "#f7faf4", layout: "majlis", image: "/assets/templates/sage-majlis.webp" },
    { id: "cathedral-gold", name: "Cathedral Gold", category: "Baptism", price: 89, tier: "Premium", description: "Sacred symmetry, cream stone, and restrained gold for church ceremonies.", accent: "#9a7436", canvas: "#d8d0bf", paper: "#fffdf7", layout: "cathedral", image: "/assets/templates/cathedral-gold.webp" },
    { id: "editorial-black", name: "Editorial Black", category: "Business", price: 89, tier: "Premium", description: "Fashion-editorial scale and sharp contrast for launches and private events.", accent: "#f0d957", canvas: "#0b0b0b", paper: "#f4f1e8", layout: "editorial", image: "/assets/templates/editorial-black.webp" },
    { id: "wildflower-arch", name: "Wildflower Arch", category: "Other Celebrations", price: 89, tier: "Premium", description: "Layered botanical color and an immersive arched invitation frame.", accent: "#a9465d", canvas: "#d7c6aa", paper: "#fffaf1", layout: "botanical", image: "/assets/templates/wildflower-arch.webp" },
    { id: "moonlit-romance", name: "Moonlit Romance", category: "Engagement", price: 89, tier: "Premium", description: "A dramatic night-sky composition with silver details and soft ceremony light.", accent: "#aebde8", canvas: "#11172a", paper: "#1b2237", layout: "moonlit", image: "/assets/templates/moonlit-romance.webp" },

    { id: "custom-atelier", name: "Custom Atelier", category: "Custom Design", price: 149, tier: "Bespoke", description: "A one-of-one art direction, cover, soundtrack, and layout prepared by Tony's studio.", accent: "#b78335", canvas: "#22282b", paper: "#f7f0e4", layout: "custom", custom: true }
  ];
});
